services:
  - type: web
    name: quan-ly-khach-hang-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: quanlykhachhang-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "30d"
      - key: JWT_COOKIE_EXPIRES
        value: "30"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"
    plan: free
    autoDeploy: true
    region: singapore
    healthCheckPath: /api/health

databases:
  - name: quanlykhachhang-db
    databaseName: quanlykhachhang
    user: quanlykhachhang_user
    plan: free
    region: singapore
